name: "CI"

on: push

jobs:
  build:
    name: "🏗️ Gradle build"
    runs-on: ubuntu-latest
    steps:
    - name: "📥 Check-out"
      uses: actions/checkout@v4
    - name: "🧰 Set up JDK 1.8"
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
    - name: "💪 Grant execute permission for gradlew"
      run: "chmod +x gradlew"
    - name: "🏗️ Build with Gradle"
      run: "./gradlew build"
  test:
    name: "✅ Gradle test"
    runs-on: ubuntu-latest
    steps:
    - name: "📥 Check-out"
      uses: actions/checkout@v4
    - name: "🧰 Set up JDK 1.8"
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
    - name: "💪 Grant execute permission for gradlew"
      run: "chmod +x gradlew"
    - name: "✅ Test with Gradle"
      run: "./gradlew test"
