name: Create release

on:
  push:
    tags: # Push events to new versions, e.g., 1.0, 20.15.10
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+-*'
    - '[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Check-out
      uses: actions/checkout@v4
    - name: 🏷️ Get version tag
      id: get-version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: ✏️ Generate changelog
      id: generate-changelog
      if: runner.os == 'Linux'
      uses: heinrichreimer/action-github-changelog-generator@v2
      with:
        onlyLastTag: true
        stripHeaders: true
        stripGeneratorNotice: true
    - name: 📤 Upload changelog
      uses: actions/upload-artifact@v4
      with:
        name: Changelog
        path: CHANGELOG.md
    - name: 🚀 Create GitHub release
      id: create-github-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get-version.outputs.tag }}
        body: ${{ steps.generate-changelog.outputs.changelog }}
        prerelease: false
  publish-plugin:
    name: 🚀 Publish plugin
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Check-out
      uses: actions/checkout@v4
    - name: 🧰 Install JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: 💪 Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: 💪 Set Gradle Plugin Plugin portal credentials
      run: |
        mkdir -p ~/.gradle
        touch ~/.gradle/gradle.properties
        echo gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} >> ~/.gradle/gradle.properties
        echo gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} >> ~/.gradle/gradle.properties
    - name: 🚀 Publish with Gradle
      run: ./gradlew publishPlugins
